baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Cygo Entrepreneur'
enableEmoji = true
relativeURLs = true
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = true
theme = "cygo"
