baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Omoo Studio - Web Design and Development services for growing startups'
enableEmoji = true
relativeURLs = true
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = true
theme = "cygo"
